[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.dependencies]
async-std = { version = "1.6", features = ["attributes"] }
async-trait = "0.1"
bytes = "1.2"
http = "1"
http-body-util = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
