[package]
name = "with-ramhorns"
version = "0.1.0"
edition = "2021"

[dependencies]
ngyn = { git = "https://github.com/ngyn-rs/ngyn", branch = "dev" }
ramhorns = { version = "1" }
tokio = { version = "1", features = ["full"] }
