name: Release Workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  crates_io_publish:
    name: Publish (crates.io)
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.75.0

      - name: cargo-release Cache
        id: cargo_release_cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-release
          key: ${{ runner.os }}-cargo-release

      - run: cargo install cargo-release cargo-expand
        if: steps.cargo_release_cache.outputs.cache-hit != 'true'

      - name: cargo login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: "cargo release publish"
        run: |-
          cargo release \
            publish \
            --manifest-path ./crates/Cargo.toml \
            --workspace \
            --all-features \
            --allow-branch main \
            --no-confirm \
            --no-verify \
            --execute
