name: Gituhb release
on:
  push:
    branches: main

jobs:
  release:
    name: Perform release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cocogitto release
        id: release
        uses: oknozor/cocogitto-action@v3
        with:
          release: true
          check-latest-tag-only: true
          git-user: 'elcharitas'
          git-user-email: 'jona'

      - name: Print version
        run: "echo '${{ steps.release.outputs.version }}'"

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
